import type { Metadata } from "next"
import Link from "next/link"

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://www.headcanonforge.com"

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Terms of Service for Headcanon Forge — rules for using our AI headcanon generator.",
  alternates: { canonical: `${siteUrl}/terms` },
  robots: { index: true, follow: true },
}

export default function TermsPage() {
  return (
    <main id="main-content" className="mx-auto max-w-3xl px-6 py-16 prose prose-gray">
      <h1>Terms of Service</h1>
      <p className="text-sm text-gray-500">Last updated: June 17, 2026</p>

      <p>
        By using Headcanon Forge at{" "}
        <a href={siteUrl}>{siteUrl.replace("https://", "")}</a>, you agree to these terms.
      </p>

      <h2>Service description</h2>
      <p>
        Headcanon Forge is an AI-powered tool for generating fictional character and relationship
        headcanons for creative inspiration. The service requires Google sign-in to generate
        content.
      </p>

      <h2>Acceptable use</h2>
      <ul>
        <li>Use the service for lawful, creative purposes only.</li>
        <li>Do not submit illegal, hateful, sexually explicit, or harassing content.</li>
        <li>Do not attempt to abuse, scrape, or overload our APIs.</li>
        <li>Respect intellectual property of original creators and fandoms.</li>
      </ul>

      <h2>AI-generated content</h2>
      <p>
        Outputs are generated by AI and may be inaccurate or inappropriate despite our filters. You
        are responsible for reviewing content before use. We provide the service &quot;as is&quot;
        without warranties.
      </p>

      <h2>Community Explore</h2>
      <p>
        If you choose to share a generation to the community Explore gallery, you grant us permission
        to display that content publicly on the site. You can keep generations private by leaving
        the share option unchecked.
      </p>

      <h2>Account</h2>
      <p>
        You sign in with Google. You are responsible for activity under your account. We may suspend
        access for violations of these terms.
      </p>

      <h2>Limitation of liability</h2>
      <p>
        To the fullest extent permitted by law, Headcanon Forge is not liable for indirect or
        consequential damages arising from use of the service.
      </p>

      <h2>Changes</h2>
      <p>We may update these terms. Continued use after changes constitutes acceptance.</p>

      <h2>Contact</h2>
      <p>
        Questions: <a href="mailto:quven2014@gmail.com">quven2014@gmail.com</a>
      </p>

      <p>
        See also our <Link href="/privacy">Privacy Policy</Link>.{" "}
        <Link href="/">← Back to Home</Link>
      </p>
    </main>
  )
}
